<#
.SYNOPSIS
  One-command Graphify refresh: builds a local AST knowledge graph of the
  current project and regenerates the report + interactive visualization.

.DESCRIPTION
  Portable by design - copy this single file into any project (root or a
  scripts/ folder) and run it from there. It only ever touches the
  directory it's invoked from (graphify extract . / graphify cluster-only .).
  No API key, no LLM cost - extraction runs entirely via local tree-sitter
  AST parsing.

  On first run in a project, seeds a starter .graphifyignore (only if one
  doesn't already exist - never overwrites) covering the build-artifact
  directories that most commonly pollute a graph with minified junk.
  Extend it with project-specific paths as needed.

  After building, does a quick sanity check on the God Nodes list: if it's
  full of short/minified-looking names like i() or n(), that's the
  tell-tale sign a build artifact slipped through - the script warns you
  so you can add it to .graphifyignore and re-run.

  Finally, runs `graphify claude install` so Claude Code actually consults
  the graph instead of raw grep/read on future sessions. This writes/merges
  a "## graphify" section into CLAUDE.md and adds a PreToolUse hook to
  .claude/settings.json (advisory only - it injects a reminder, it never
  blocks a tool call; see graphify's own source for the fail-open guard).
  Both operations are idempotent - re-running when already installed prints
  "no change" and touches nothing. Skipped automatically if the current
  directory isn't a git root (the most common way to install this into the
  wrong CLAUDE.md - it must run from the same directory Claude Code treats
  as the project root, not a subfolder).

.PARAMETER Label
  Also name communities with an LLM (costs tokens; needs an API key
  configured for graphify). Default: off (--no-label, fully free).

.PARAMETER NoOpen
  Skip auto-opening graph.html in the default browser when done.

.PARAMETER NoClaudeInstall
  Skip the `graphify claude install` step (CLAUDE.md section + PreToolUse
  hook). Use this if you don't want Claude Code wired to the graph, or want
  to review the graph output before opting in.

.EXAMPLE
  .\graphify-refresh.ps1
  Rebuilds the graph for the current directory, wires up Claude Code, and
  opens the result.

.EXAMPLE
  .\graphify-refresh.ps1 -NoOpen
  Rebuilds without opening a browser (useful for scripted/CI runs).
#>
[CmdletBinding()]
param(
    [switch]$Label,
    [switch]$NoOpen,
    [switch]$NoClaudeInstall
)

$ErrorActionPreference = 'Stop'

# ---- Locate graphify: PATH first, then the default uv tool-install location ----
$cmd = Get-Command graphify -ErrorAction SilentlyContinue
if ($cmd) {
    $graphifyExe = $cmd.Source
} else {
    $fallback = Join-Path $env:USERPROFILE '.local\bin\graphify.exe'
    if (Test-Path $fallback) {
        $graphifyExe = $fallback
    } else {
        Write-Error "graphify not found on PATH or at $fallback. Install once with: python -m pip install --user uv ; python -m uv tool install graphifyy"
        exit 1
    }
}

$root = Get-Location
Write-Host "Graphify refresh - $root" -ForegroundColor Cyan

# ---- Seed a starter .graphifyignore on first run only ----
$ignoreFile = Join-Path $root '.graphifyignore'
if (-not (Test-Path $ignoreFile)) {
    $starterIgnore = @'
# Auto-generated by graphify-refresh.ps1 - extend with project-specific paths.
# These are common build-artifact / vendored-code locations that pollute the
# graph with minified junk if left in. Tell-tale sign: God Nodes full of
# short names like i()/n()/t() instead of real function/class names.
dist/
build/
out/
target/
bin/
obj/
coverage/
.next/
.nuxt/
vendor/
android/app/src/main/assets/public/
android/app/build/
ios/App/App/public/
__pycache__/
.venv/
venv/
*.min.js
'@
    $starterIgnore | Out-File -FilePath $ignoreFile -Encoding utf8
    Write-Host "Created starter .graphifyignore - review/extend it if your project has other build outputs." -ForegroundColor Yellow
}

# ---- Extract (local AST, no LLM, no API key) ----
Write-Host ""
Write-Host "[1/3] Extracting (local AST parsing)..." -ForegroundColor Cyan
& $graphifyExe extract . --code-only
if ($LASTEXITCODE -ne 0) { Write-Error "graphify extract failed (exit $LASTEXITCODE)"; exit $LASTEXITCODE }

# ---- Cluster + report + visualization ----
Write-Host ""
Write-Host "[2/3] Building report + visualization..." -ForegroundColor Cyan
if ($Label) {
    & $graphifyExe cluster-only .
} else {
    & $graphifyExe cluster-only . --no-label
}
if ($LASTEXITCODE -ne 0) { Write-Error "graphify cluster-only failed (exit $LASTEXITCODE)"; exit $LASTEXITCODE }

$reportPath = Join-Path $root 'graphify-out\GRAPH_REPORT.md'
$graphPath  = Join-Path $root 'graphify-out\graph.html'

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "  Report: $reportPath"
Write-Host "  Graph:  $graphPath"

# ---- Pollution sanity check: warn if God Nodes look minified ----
if (Test-Path $reportPath) {
    $reportText = Get-Content $reportPath -Raw
    if ($reportText -match '(?s)## God Nodes.*?(?=\n## )') {
        $godNodesText = $Matches[0]
        if ($godNodesText -match '`[a-zA-Z]{1,2}\(\)`') {
            Write-Host ""
            Write-Host "WARNING: God Nodes contain short/minified-looking names (e.g. i(), n(), t())." -ForegroundColor Yellow
            Write-Host "  This usually means a build artifact or bundled/minified file got indexed." -ForegroundColor Yellow
            Write-Host "  Add its path to .graphifyignore and re-run this script." -ForegroundColor Yellow
        }
    }
}

# ---- Wire up Claude Code: CLAUDE.md section + advisory PreToolUse hook ----
# Idempotent (re-running prints "no change") so it's safe to do on every refresh.
# Guarded by a git-root check: this must run from the same directory Claude Code
# treats as the project root, or it writes a CLAUDE.md/.claude that never gets read.
if (-not $NoClaudeInstall) {
    Write-Host ""
    if (Test-Path (Join-Path $root '.git')) {
        Write-Host "[3/3] Wiring up Claude Code (CLAUDE.md + PreToolUse hook)..." -ForegroundColor Cyan
        & $graphifyExe claude install
        if ($LASTEXITCODE -ne 0) { Write-Warning "graphify claude install failed (exit $LASTEXITCODE) - continuing anyway" }
    } else {
        Write-Host "[3/3] Skipped Claude Code wiring: $root has no .git - this doesn't look like the project root." -ForegroundColor Yellow
        Write-Host "  Run this script from the actual repo root, or pass -NoClaudeInstall to silence this." -ForegroundColor Yellow
    }
}

if (-not $NoOpen -and (Test-Path $graphPath)) {
    Start-Process $graphPath
}
